import 'server-only'

import type { Audit, AuditIssue } from '@/db/schema'

type ExportableAudit = Pick<
  Audit,
  'url' | 'score' | 'summary' | 'createdAt' | 'issues'
>

/**
 * Plain-text exporters. The PDF version lives in pdf-report.tsx because
 * @react-pdf/renderer needs JSX. These two are pure string builders so
 * tests can hit them without a renderer.
 */

const SEVERITY_LABEL = {
  error: 'Critical',
  warning: 'Note',
  good: 'Pass',
} as const

const SEVERITY_ICON = {
  error: '✗',
  warning: '!',
  good: '✓',
} as const

function unkebab(key: string) {
  return key
    .replace(/-/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase())
}

function formatDate(d: Date) {
  return d.toISOString().split('T')[0]
}

function scoreLabel(score: number | null) {
  if (score === null) return 'No score'
  if (score >= 90) return 'Excellent'
  if (score >= 75) return 'Good'
  if (score >= 50) return 'Needs work'
  if (score >= 25) return 'Rough'
  return 'Critical'
}

export function toMarkdown(audit: ExportableAudit): string {
  const issues = (audit.issues ?? []) as AuditIssue[]
  const grouped = {
    error: issues.filter((i) => i.severity === 'error'),
    warning: issues.filter((i) => i.severity === 'warning'),
    good: issues.filter((i) => i.severity === 'good'),
  }

  const lines: string[] = []
  lines.push(`# Landingcheck audit — ${audit.url}`)
  lines.push('')
  lines.push(`**Score:** ${audit.score ?? '—'} / 100 — ${scoreLabel(audit.score)}  `)
  lines.push(`**Audited:** ${formatDate(audit.createdAt)}  `)
  lines.push(`**URL:** <${audit.url}>`)
  lines.push('')
  if (audit.summary) {
    lines.push(`> ${audit.summary}`)
    lines.push('')
  }
  lines.push(
    `**${grouped.error.length}** critical · **${grouped.warning.length}** warnings · **${grouped.good.length}** passing`,
  )
  lines.push('')

  const renderGroup = (title: string, list: AuditIssue[]) => {
    if (list.length === 0) return
    lines.push(`## ${title}`)
    lines.push('')
    for (const i of list) {
      lines.push(`- **${unkebab(i.key)}** — ${i.message}`)
    }
    lines.push('')
  }

  renderGroup('Critical', grouped.error)
  renderGroup('Needs work', grouped.warning)
  renderGroup('Passing', grouped.good)

  lines.push('---')
  lines.push(`*Generated by [Landingcheck](https://landingcheck.app) on ${formatDate(new Date())}*`)
  lines.push('')

  return lines.join('\n')
}

/**
 * RFC-4180 compliant cell quoting. Only quotes when needed; doubles
 * embedded quotes; preserves Unicode.
 */
function csvCell(input: string | number | null | undefined): string {
  const s = input == null ? '' : String(input)
  if (/[",\n\r]/.test(s)) {
    return `"${s.replace(/"/g, '""')}"`
  }
  return s
}

export function toCsv(audit: ExportableAudit): string {
  const issues = (audit.issues ?? []) as AuditIssue[]
  const rows: string[] = []
  rows.push(['url', 'score', 'audited_at', 'severity', 'key', 'message'].join(','))
  for (const i of issues) {
    rows.push(
      [
        csvCell(audit.url),
        csvCell(audit.score),
        csvCell(audit.createdAt.toISOString()),
        csvCell(SEVERITY_LABEL[i.severity]),
        csvCell(i.key),
        csvCell(i.message),
      ].join(','),
    )
  }
  return rows.join('\n')
}

/**
 * Helper used by the PDF renderer too — keeps severity icon mapping
 * in one place.
 */
export const exportHelpers = {
  unkebab,
  scoreLabel,
  formatDate,
  SEVERITY_LABEL,
  SEVERITY_ICON,
}
